### ISSUE TITLE
Setting password doesn't work

### ISSUE THREAD

**Issue by haf** [sansible/users_and_groups#25]
I have a user with a declared password, that executes like so:

```
TASK [sansible.users_and_groups : Manage systems users] ************************
ok: [default] => (item={u'home': u'/home/myuser', u'shell': u'/usr/sbin/nologin', u'password': u'sOmEPaSS1', u'name': u'myuser', u'groups': [u'sftp-only']})
```

With this config:

```
users_and_groups:
  authorized_keys_dir: /etc/ssh/authorized_keys
  groups:
  - name: sftp-only
  - name: operations
  users:
  - name: myuser
    groups:
    - sftp-only
    home: /home/myuser
    shell: /usr/sbin/nologin
    password: sOmEPaSS1
```

But it turns out that the user cannot log in using that password. However, running this command:

```
sudo passwd myuser
... UNIX password: sOmEPaSS1
...
```

Makes it all work. My conclusion is that the password isn't property set on the user.

After running `passwd` and then testing (OK), and then running ansible again, this role/repo resets the password to something else.

I've disabled strong passwords and I'm trying to set a 8-char alphanumeric password. To re-iterate, it works with `passwd` but not with this module.

Expected behaviour: setting passwords with this module should work.

This issue may be a [documentation issue](https://stackoverflow.com/a/36824852/63621)
