### ISSUE TITLE
Enable include of /etc/sudoers.d

### ISSUE THREAD

**Issue by patchy-txr** [sansible/users_and_groups#28]
Hi, 

Thank you, I found your role very usefull.
One thing i didn't understood, why you tried to add a commented line instead of enabling it: "includedir /etc/sudoers.d" 

```YAML
- name: Enable include of /etc/sudoers.d
  become: yes
  lineinfile:
    name: /etc/sudoers
    regexp: "^#includedir"
    line: "#includedir /etc/sudoers.d"
    state: present
```
