### ISSUE TITLE
Bug when using `group` and `ssh_key`

### ISSUE THREAD

**Issue by wojtek-oledzki** [sansible/users_and_groups#8]
Errors when using `group` and `ssh_key`

``` YAML
- role: sansible.users_and_groups
  users_and_groups:
    groups:
      - name: voluptatem
    users:
      - name: iste.natus
        group: voluptatem
        ssh_key: ./lorem.ipsum.pub
```

Error:

```
TASK [sansible.users_and_groups : Create .ssh directory] ***********************
failed: [default] => (item={u'group': u'voluptatem', u'name': u'iste.natus', u'ssh_key': u'./lorem.ipsum.pub'}) => {"failed": true, "gid": 0, "group": "root", "item": {"group": "voluptatem", "name": "iste.natus", "ssh_key": "./lorem.ipsum.pub"}, "mode": "0755", "msg": "chgrp failed: failed to look up group iste.natus", "owner": "iste.natus", "path": "/home/iste.natus/.ssh", "size": 4096, "state": "directory", "uid": 1005}
```
